const char *mips_script = "/* $Id$ */\n"
"\n"
"OUTPUT_FORMAT(\"elf32-tradbigmips\", \"elf32-tradbigmips\", \"elf32-tradlittlemips\")\n"
"OUTPUT_ARCH(mips)\n"
"ENTRY(_start)\n"
"SEARCH_DIR(\"/lib\"); SEARCH_DIR(\"/usr/lib\");\n"
"SECTIONS {\n"
"	 PROVIDE (__executable_start = 0x00400000);\n"
"	 . = 0x00400000 + SIZEOF_HEADERS;\n"
"	.interp		: { *(.interp) }\n"
"	.hash		: { *(.hash) }\n"
"	.dynsym		: { *(.dynsym) }\n"
"	.dynstr		: { *(.dynstr) }\n"
"	.gnu.version	: { *(.gnu.version) }\n"
"	.gnu.version_d	: { *(.gnu.version_d) }\n"
"	.gnu.version_r	: { *(.gnu.version_r) }\n"
"	.rel.dyn        :\n"
"	{\n"
"		*(.rel.init)\n"
"		*(.rel.text .rel.text.* .rel.gnu.linkonce.t.*)\n"
"		*(.rel.fini)\n"
"		*(.rel.rodata .rel.rodata.* .rel.gnu.linkonce.r.*)\n"
"		*(.rel.data .rel.data.* .rel.gnu.linkonce.d.*)\n"
"		*(.rel.tdata .rel.tdata.* .rel.gnu.linkonce.td.*)\n"
"		*(.rel.tbss .rel.tbss.* .rel.gnu.linkonce.tb.*)\n"
"		*(.rel.ctors)\n"
"		*(.rel.dtors)\n"
"		*(.rel.got)\n"
"		*(.rel.bss .rel.bss.* .rel.gnu.linkonce.b.*)\n"
"	}\n"
"	.rela.dyn	:\n"
"	{\n"
"		*(.rela.init)\n"
"		*(.rela.text .rela.text.* .rela.gnu.linkonce.t.*)\n"
"		*(.rela.fini)\n"
"		*(.rela.rodata .rela.rodata.* .rela.gnu.linkonce.r.*)\n"
"		*(.rela.data .rela.data.* .rela.gnu.linkonce.d.*)\n"
"		*(.rela.tdata .rela.tdata.* .rela.gnu.linkonce.td.*)\n"
"		*(.rela.tbss .rela.tbss.* .rela.gnu.linkonce.tb.*)\n"
"		*(.rela.ctors)\n"
"		*(.rela.dtors)\n"
"		*(.rela.got)\n"
"		*(.rela.bss .rela.bss.* .rela.gnu.linkonce.b.*)\n"
"	}\n"
"	.rel.plt	: { *(.rel.plt) }\n"
"	.rela.plt	: { *(.rela.plt) }\n"
"	.init		:\n"
"	{\n"
"		KEEP(*(.init))\n"
"	} = 0x00000000\n"
"	.plt		: { *(.plt) }\n"
"	.text		:\n"
"	{\n"
"		*(.text .stub .text.* .gnu.linkonce.t.*)\n"
"	} = 0x00000000\n"
"	.fini		:\n"
"	{\n"
"		KEEP(*(.fini))\n"
"	} = 0x00000000\n"
"	PROVIDE(__etext = .);\n"
"	PROVIDE(_etext = .);\n"
"	PROVIDE(etext = .);\n"
"	.rodata		: { *(.rodata .rodata.* .gnu.linkonce.r.*) }\n"
"	.rodata1	: { *(.rodata1) }\n"
"	.eh_frame_hdr	: { *(.eh_frame_hdr) }\n"
"	.eh_frame	: { KEEP(*(.eh_frame)) }\n"
"	.gcc_except_table   : { *(.gcc_except_table) }\n"
"	. = ALIGN (CONSTANT(COMMONPAGESIZE)) - ((CONSTANT(COMMONPAGESIZE) - .) & (CONSTANT(COMMONPAGESIZE) - 1));\n"
"	. = DATA_SEGMENT_ALIGN (CONSTANT(COMMONPAGESIZE), CONSTANT(COMMONPAGESIZE));\n"
"	. = ALIGN(32 / 8);\n"
"	.tdata		: { *(.tdata .tdata.* .gnu.linkonce.td.*) }\n"
"	.tbss		: { *(.tbss .tbss.* .gnu.linkonce.tb.*) *(.tcommon) }\n"
"	PROVIDE(__preinit_array_start = .);\n"
"	.preinit_array	: { *(.preinit_array) }\n"
"	PROVIDE(__preinit_array_end = .);\n"
"	PROVIDE(__init_array_start = .);\n"
"	.init_array	: { *(.init_array) }\n"
"	PROVIDE(__init_array_end = .);\n"
"	PROVIDE(__fini_array_start = .);\n"
"	.fini_array	: { *(.fini_array) }\n"
"	PROVIDE(__fini_array_end = .);\n"
"	.dynamic	: { *(.dynamic) }\n"
"	.ctors		:\n"
"	{\n"
"		KEEP(*crtbegin*.o(.ctors))\n"
"		KEEP(*(EXCLUDE_FILE (*crtend*.o ) .ctors))\n"
"		KEEP(*(SORT(.ctors.*)))\n"
"		KEEP(*(.ctors))\n"
"	}\n"
"	.dtors		:\n"
"	{\n"
"		KEEP(*crtbegin*.o(.dtors))\n"
"		KEEP(*(EXCLUDE_FILE (*crtend*.o ) .dtors))\n"
"		KEEP(*(SORT(.dtors.*)))\n"
"		KEEP(*(.dtors))\n"
"	}\n"
"	.jcr		: { KEEP(*(.jcr)) }\n"
"	.got		: { *(.got.plt) *(.got) }\n"
"	.data		:\n"
"	{\n"
"		*(.data .data.* .gnu.linkonce.d.*)\n"
"		SORT(CONSTRUCTORS)\n"
"	}\n"
"	.data1		: { *(.data1) }\n"
"	_edata = .;\n"
"	PROVIDE(edata = .);\n"
"	__bss_start = .;\n"
"	.bss		:\n"
"	{\n"
"		*(.dynbss)\n"
"		*(.bss .bss.* .gnu.linkonce.b.*)\n"
"		*(COMMON)\n"
"		. = ALIGN(32 / 8);\n"
"	}\n"
"	. = ALIGN(32 / 8);\n"
"	_end = .;\n"
"	PROVIDE(end = .);\n"
"	. = DATA_SEGMENT_END (.);\n"
"\n"
"	.stab		0 : { *(.stab) }\n"
"	.stabstr	0 : { *(.stabstr) }\n"
"	.stab.excl	0 : { *(.stab.excl) }\n"
"	.stab.exclstr	0 : { *(.stab.exclstr) }\n"
"	.stab.index	0 : { *(.stab.index) }\n"
"	.stab.indexstr	0 : { *(.stab.indexstr) }\n"
"	.comment	0 : { *(.comment) }\n"
"\n"
"	/* DWARF1 */\n"
"	.debug		0 : { *(.debug) }\n"
"	.line		0 : { *(.line) }\n"
"\n"
"	/* GNU DWARF1 Extension */\n"
"	.debug_srcinfo	0 : { *(.debug_srcinfo) }\n"
"	.debug_sfnames	0 : { *(.debug_sfnames) }\n"
"\n"
"	/* DWARF2 */\n"
"	.debug_aranges	0 : { *(.debug_aranges) }\n"
"	.debug_pubnames 0 : { *(.debug_pubnames) }\n"
"	.debug_info	0 : { *(.debug_info .gnu.linkonce.wi.*) }\n"
"	.debug_abbrev	0 : { *(.debug_abbrev) }\n"
"	.debug_line	0 : { *(.debug_line) }\n"
"	.debug_frame	0 : { *(.debug_frame) }\n"
"	.debug_str	0 : { *(.debug_str) }\n"
"	.debug_loc	0 : { *(.debug_loc) }\n"
"	.debug_macinfo	0 : { *(.debug_macinfo) }\n"
"\n"
"	/DISCARD/	: { *(.note.GNU-stack) }\n"
"}\n"
;
